import Head from "next/head";
import LandingText from "~/components/layout/landingtext";

export default function Home() {
  return (
    <>
      <Head>
        <title>WebWay</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <main>
        <LandingText />
      </main>
    </>
  );
}
